"""Canonical machine-readable VOIAGE analysis contracts."""

# pyright: reportUnknownVariableType=false

from .adapters import (
    LegacyBackendAdapter,
    adapt_backend,
    adapt_parameter_set,
    adapt_value_array,
    analysis_spec_from_inputs,
    analysis_spec_from_prepared_inputs,
)
from .analysis import (
    AnalysisResult,
    AnalysisSpec,
    ContractModel,
    DiagnosticEnvelope,
    DiagnosticRecord,
    InterchangeIdentity,
    NumericalPolicy,
    ParameterSpec,
    Provenance,
    RunContext,
    ScalarPayload,
)
from .bundle import (
    BundleVerificationError,
    ContractPerformanceBudget,
    SchemaEvolutionReport,
    VerifiedContractBundle,
    canonical_bundle_digest,
    validate_schema_evolution,
    verify_contract_bundle,
    verify_pinned_contract_bundle,
)
from .capabilities import (
    BackendCapabilities,
    Capability,
    CapabilityBackend,
    CapabilityReport,
    KernelRequirements,
    UnsupportedCapabilityError,
    evaluate_backend,
    select_backend,
)
from .concerns import ConcernSpec, EvidenceReference
from .estimation import (
    ConditioningSpec,
    EstimationTargetSpec,
    EstimationVarianceDiagnostics,
    EstimationVarianceProvenance,
    EstimationVarianceResult,
    EstimationVarianceSpec,
    EstimatorAssuranceSpec,
    SamplingModelSpec,
)
from .interchange import (
    analysis_result_table,
    schema_fingerprint,
    write_analysis_result_ipc,
    write_analysis_result_parquet,
)
from .kernel import CalculationKernel, EvpiKernel, dispatch_calculation, run_evpi
from .normalized_input import (
    BindingProfile,
    DatasetManifest,
    FieldManifest,
    IngestionDiagnostic,
    KeyReference,
    NormalizedInputBundle,
    ResourceManifest,
    SourceProvenance,
    TableManifest,
    VOIBinding,
)
from .perspective import PerspectivePayload, adapt_perspective_result, run_perspective
from .preparation import (
    DataQualityReport,
    MethodInputCapability,
    PreparedAnalysisInputs,
    method_input_capability,
    prepare_analysis_inputs,
)
from .risk_sensitive_voi import (
    RISK_SENSITIVE_VOI_INPUT_SCHEMA_V1,
    RISK_SENSITIVE_VOI_RESULT_SCHEMA_V1,
    validate_risk_sensitive_voi_result,
    validate_risk_sensitive_voi_semantics,
)
from .signed_social_information import (
    SIGNED_SOCIAL_INFORMATION_INPUT_SCHEMA_V1,
    SIGNED_SOCIAL_INFORMATION_RESULT_SCHEMA_V1,
    validate_signed_social_information_result,
    validate_signed_social_information_semantics,
)
from .study_design import (
    CossCurvePointV1,
    CossPlotDataV1,
    CossResultV1,
    FeasibleDesignRangeV1,
    InformationEfficiencyResultV1,
    InformationValueInputV1,
    SelectionUncertaintyV1,
    StudyDesignContextV1,
    StudyDesignPointInputV1,
)
from .study_portfolio import (
    CossPortfolioCandidateV1,
    PortfolioCapacityConstraintV1,
    StudyPortfolioEvaluationV1,
    StudyPortfolioResultV1,
)

__all__ = [
    "RISK_SENSITIVE_VOI_INPUT_SCHEMA_V1",
    "RISK_SENSITIVE_VOI_RESULT_SCHEMA_V1",
    "SIGNED_SOCIAL_INFORMATION_INPUT_SCHEMA_V1",
    "SIGNED_SOCIAL_INFORMATION_RESULT_SCHEMA_V1",
    "AnalysisResult",
    "AnalysisSpec",
    "BackendCapabilities",
    "BindingProfile",
    "BundleVerificationError",
    "CalculationKernel",
    "Capability",
    "CapabilityBackend",
    "CapabilityReport",
    "ConcernSpec",
    "ConditioningSpec",
    "ContractModel",
    "ContractPerformanceBudget",
    "CossCurvePointV1",
    "CossPlotDataV1",
    "CossPortfolioCandidateV1",
    "CossResultV1",
    "DataQualityReport",
    "DatasetManifest",
    "DiagnosticEnvelope",
    "DiagnosticRecord",
    "EstimationTargetSpec",
    "EstimationVarianceDiagnostics",
    "EstimationVarianceProvenance",
    "EstimationVarianceResult",
    "EstimationVarianceSpec",
    "EstimatorAssuranceSpec",
    "EvidenceReference",
    "EvpiKernel",
    "FeasibleDesignRangeV1",
    "FieldManifest",
    "InformationEfficiencyResultV1",
    "InformationValueInputV1",
    "IngestionDiagnostic",
    "InterchangeIdentity",
    "KernelRequirements",
    "KeyReference",
    "LegacyBackendAdapter",
    "MethodInputCapability",
    "NormalizedInputBundle",
    "NumericalPolicy",
    "ParameterSpec",
    "PerspectivePayload",
    "PortfolioCapacityConstraintV1",
    "PreparedAnalysisInputs",
    "Provenance",
    "ResourceManifest",
    "RunContext",
    "SamplingModelSpec",
    "ScalarPayload",
    "SchemaEvolutionReport",
    "SelectionUncertaintyV1",
    "SourceProvenance",
    "StudyDesignContextV1",
    "StudyDesignPointInputV1",
    "StudyPortfolioEvaluationV1",
    "StudyPortfolioResultV1",
    "TableManifest",
    "UnsupportedCapabilityError",
    "VOIBinding",
    "VerifiedContractBundle",
    "adapt_backend",
    "adapt_parameter_set",
    "adapt_perspective_result",
    "adapt_value_array",
    "analysis_result_table",
    "analysis_spec_from_inputs",
    "analysis_spec_from_prepared_inputs",
    "canonical_bundle_digest",
    "dispatch_calculation",
    "evaluate_backend",
    "method_input_capability",
    "prepare_analysis_inputs",
    "run_evpi",
    "run_perspective",
    "schema_fingerprint",
    "select_backend",
    "validate_risk_sensitive_voi_result",
    "validate_risk_sensitive_voi_semantics",
    "validate_schema_evolution",
    "validate_signed_social_information_result",
    "validate_signed_social_information_semantics",
    "verify_contract_bundle",
    "verify_pinned_contract_bundle",
    "write_analysis_result_ipc",
    "write_analysis_result_parquet",
]
