"""Lazy public exports for Value of Information methods.

The stable kernel imports method facades directly.  Optional and experimental
methods remain discoverable through this compatibility namespace without being
imported during ``import voiage``.
"""

from importlib import import_module

_MODULES = (
    "adaptive",
    "adaptive_learning_bandit",
    "ai_assisted_evidence_triage",
    "ambiguity_distribution_shift",
    "basic",
    "calibration",
    "capacity_budget_constrained",
    "causal_transportability",
    "ceaf",
    "computational",
    "data_quality",
    "distributional",
    "dominance",
    "dynamic_real_options",
    "equity_information",
    "evidence_obsolescence_refresh",
    "expert_synthesis",
    "explainability_transparency",
    "federated_privacy_preserving",
    "heterogeneity",
    "implementation",
    "implementation_strategy",
    "interoperability_standardization",
    "monitoring_surveillance",
    "network_nma",
    "observational",
    "perspective",
    "portfolio",
    "preference",
    "regulatory_market_access",
    "replication_reproducibility",
    "sample_information",
    "sequential",
    "strategic_behavior",
    "structural",
    "threshold",
    "validation",
)


def __getattr__(name: str) -> object:
    """Resolve a method export only when requested."""
    for module_name in _MODULES:
        module = import_module(f".{module_name}", __name__)
        if hasattr(module, name):
            value = getattr(module, name)
            globals()[name] = value
            return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [  # noqa: RUF022 - public export order is a compatibility contract
    "AIAssistedEvidenceTriageResult",
    "AdaptiveLearningBanditResult",
    "AmbiguityDistributionShiftResult",
    "CEAFResult",
    "CapacityBudgetConstrainedResult",
    "CausalTransportabilityResult",
    "ComputationalResult",
    "DataQualityResult",
    "DistributionalEquityResult",
    "DominanceResult",
    "DynamicRealOptionsResult",
    "ExpectedLossResult",
    "EquityInformationResult",
    "EvidenceObsolescenceRefreshResult",
    "ExpertSynthesisResult",
    "ExplainabilityTransparencyResult",
    "FederatedPrivacyPreservingResult",
    "HeterogeneityResult",
    "ImplementationAdjustedResult",
    "ImplementationStrategyComparisonResult",
    "InteroperabilityStandardizationResult",
    "ModelValidationResult",
    "MonitoringSurveillanceResult",
    "Perspective",
    "PerspectiveSet",
    "PreferenceHeterogeneityResult",
    "PreferenceProfile",
    "PreferenceProfileSet",
    "RegulatoryMarketAccessResult",
    "ReplicationReproducibilityResult",
    "StrategicBehaviorResult",
    "ThresholdProfile",
    "ThresholdProfileSet",
    "ThresholdResult",
    "ValidationProfile",
    "ValidationProfileSet",
    "ValueOfPerspectiveResult",
    "adaptive_evsi",
    "calculate_ceaf",
    "calculate_dominance",
    "calculate_extended_dominance",
    "calculate_icers",
    "calculate_strong_dominance",
    "cost_effectiveness_frontier",
    "enbs",
    "expected_loss",
    "evpi",
    "evppi",
    "evsi",
    "evsi_nma",
    "identify_optimal_subgroups",
    "perspective_optimal_strategies",
    "perspective_arrow_schema_fingerprint",
    "perspective_result_to_arrow",
    "portfolio_voi",
    "preference_optimal_strategies",
    "sequential_voi",
    "structural_evpi",
    "structural_evppi",
    "value_of_adaptive_learning_bandit",
    "value_of_ai_assisted_evidence_triage",
    "value_of_ambiguity_distribution_shift",
    "value_of_capacity_budget_constrained",
    "value_of_causal_transportability",
    "value_of_computational_refinement",
    "value_of_data_quality",
    "value_of_distributional_equity",
    "value_of_dynamic_real_options",
    "value_of_equity_information",
    "value_of_evidence_obsolescence_refresh",
    "value_of_expert_synthesis",
    "value_of_explainability_transparency",
    "value_of_federated_privacy_preserving",
    "value_of_heterogeneity",
    "value_of_implementation",
    "value_of_implementation_strategy_comparison",
    "value_of_interoperability_standardization",
    "value_of_model_validation",
    "value_of_monitoring_surveillance",
    "value_of_perspective",
    "write_perspective_result_ipc",
    "write_perspective_result_parquet",
    "value_of_preference",
    "value_of_preference_heterogeneity",
    "value_of_preference_information",
    "value_of_regulatory_market_access",
    "value_of_replication_reproducibility",
    "value_of_strategic_behavior",
    "value_of_threshold",
    "value_of_threshold_information",
    "value_of_validation",
    "voi_calibration",
    "voi_observational",
]
