# voiage/methods/adaptive.py

"""Value of information helpers for adaptive trial designs.

The main entry point is ``adaptive_evsi``, which estimates the value of
sample information under user-supplied adaptive trial rules.
"""

from collections.abc import Callable
from typing import Any

import numpy as np

from voiage.exceptions import InputError, raise_input_error
from voiage.schema import ParameterSet as PSASample
from voiage.schema import TrialDesign
from voiage.schema import ValueArray as NetBenefitArray

# Type alias for a function that simulates an adaptive trial and evaluates outcomes.
# This is extremely complex, involving:
# - Simulating patient recruitment and data accrual over time.
# - Applying interim analysis rules.
# - Making decisions (e.g., stop/continue, change sample size).
# - If trial completes, updating beliefs and evaluating economic model.
# - If trial stops early, evaluating economic model based on that decision.
AdaptiveTrialEconomicSim = Callable[
    [
        PSASample,
        TrialDesign,
        dict[str, Any],
    ],  # Prior PSA, Base TrialDesign, Adaptive Rules
    NetBenefitArray,  # Expected NB conditional on the full adaptive trial outcome
]


def sophisticated_adaptive_trial_simulator(
    psa_samples: PSASample, base_design: TrialDesign, adaptive_rules: dict[str, object]
) -> NetBenefitArray:
    """Simulate an adaptive trial and return net-benefit samples.

    Parameters
    ----------
    psa_samples : ParameterSet
        PSA samples representing parameter uncertainty.
    base_design : TrialDesign
        Trial design before adaptive modifications.
    adaptive_rules : dict[str, object]
        Rules describing interim analyses and early stopping behavior.

    Returns
    -------
    ValueArray
        Net-benefit samples for the decision alternatives generated by the
        simulated adaptive trial.

    Notes
    -----
    This helper is intentionally simplified and deterministic enough for
    testing and examples, not for production trial simulation.
    """
    n_samples = psa_samples.n_samples

    # Extract relevant parameters
    treatment_effect = psa_samples.parameters.get(
        "treatment_effect", np.random.normal(0.1, 0.05, n_samples)
    )
    control_rate = psa_samples.parameters.get(
        "control_rate", np.random.normal(0.3, 0.05, n_samples)
    )
    cost_per_patient = psa_samples.parameters.get(
        "cost_per_patient", np.random.normal(5000, 500, n_samples)
    )

    # Simulate trial outcomes for each sample
    n_strategies = 2  # Control and Treatment
    net_benefits = np.zeros((n_samples, n_strategies))

    # Simulate base trial outcomes
    # In a real implementation, this would involve complex trial simulation
    # For this example, we'll use a simplified approach

    # Simulate treatment outcomes
    treatment_rate = control_rate + treatment_effect
    # Ensure rates are between 0 and 1
    treatment_rate = np.clip(treatment_rate, 0, 1)
    control_rate = np.clip(control_rate, 0, 1)

    # Simulate some data to make the analysis more realistic
    n_patients_per_arm = 100  # Base sample size per arm
    treatment_outcomes = np.random.binomial(n_patients_per_arm, treatment_rate)
    control_outcomes = np.random.binomial(n_patients_per_arm, control_rate)

    # Calculate trial costs
    total_patients = sum(arm.sample_size for arm in base_design.arms)
    _ = total_patients * cost_per_patient  # Calculate trial costs

    # Apply adaptive rules
    interim_points = adaptive_rules.get("interim_analysis_points", [])
    early_stopping = adaptive_rules.get("early_stopping_rules", {})

    # Simulate interim analyses
    adjusted_sample_size = np.full(n_samples, total_patients, dtype=int)

    if early_stopping and interim_points:
        efficacy_threshold = early_stopping.get("efficacy", 0.95)
        futility_threshold = early_stopping.get("futility", 0.1)

        interim_treatment_rate = treatment_outcomes / n_patients_per_arm
        interim_control_rate = control_outcomes / n_patients_per_arm
        interim_effect = interim_treatment_rate - interim_control_rate

        stop_condition = (interim_effect > efficacy_threshold) | (
            interim_effect < futility_threshold
        )

        first_valid_interim = None
        for interim_point in interim_points:
            if int(n_patients_per_arm * interim_point) > 0:
                first_valid_interim = interim_point
                break

        if first_valid_interim is not None:
            adjusted_val = int(total_patients * first_valid_interim)
            adjusted_sample_size = np.where(
                stop_condition, adjusted_val, adjusted_sample_size
            )

    # Adjust costs based on early stopping
    adjusted_cost = adjusted_sample_size * cost_per_patient

    # Calculate net benefits for each strategy with more realistic values
    # Strategy 0: Control only
    control_benefit = control_outcomes * 1000  # Benefit per successful outcome
    net_benefits[:, 0] = control_benefit - adjusted_cost

    # Strategy 1: Treatment
    # Benefit is proportional to treatment effect
    treatment_benefit = treatment_outcomes * 1000  # Benefit per successful outcome
    net_benefits[:, 1] = treatment_benefit - adjusted_cost

    # Add some noise to make the differences more pronounced
    net_benefits += np.random.normal(0, 500, net_benefits.shape)

    # Create ValueArray
    import xarray as xr

    dataset = xr.Dataset(
        {"net_benefit": (("n_samples", "n_strategies"), net_benefits)},
        coords={
            "n_samples": np.arange(n_samples),
            "n_strategies": np.arange(n_strategies),
            "strategy": ("n_strategies", ["Control Only", "With Treatment"]),
        },
    )
    return NetBenefitArray(dataset=dataset)


def _simulate_trial_and_interims(
    true_treatment_rate: float,
    true_cr: float,
    n_patients_per_arm: int,
    adaptive_rules: dict[str, object],
) -> tuple[int, int, int]:
    """Simulate trial data and apply interim analysis rules."""
    # Simulate full trial data
    treatment_outcomes = np.random.binomial(n_patients_per_arm, true_treatment_rate)
    control_outcomes = np.random.binomial(n_patients_per_arm, true_cr)

    # Apply adaptive rules
    interim_points = adaptive_rules.get("interim_analysis_points", [])
    early_stopping = adaptive_rules.get("early_stopping_rules", {})

    adjusted_sample_size = 2 * n_patients_per_arm  # Total patients (both arms)

    if isinstance(interim_points, list):
        for interim_point in interim_points:
            # At interim analysis, decide whether to stop early
            if early_stopping and isinstance(early_stopping, dict):
                efficacy_threshold = early_stopping.get("efficacy", 0.95)
                futility_threshold = early_stopping.get("futility", 0.1)

                # Calculate interim treatment effect based on partial data
                interim_n = max(1, int(n_patients_per_arm * interim_point))
                interim_treatment_outcomes = np.random.binomial(
                    interim_n, true_treatment_rate
                )
                interim_control_outcomes = np.random.binomial(interim_n, true_cr)

                # Calculate interim effect (simplified)
                if interim_n > 0:
                    interim_treatment_rate = interim_treatment_outcomes / interim_n
                    interim_control_rate = interim_control_outcomes / interim_n
                    interim_effect = interim_treatment_rate - interim_control_rate

                    # Make decision based on interim effect
                    if interim_effect > efficacy_threshold:
                        # Stop for efficacy
                        adjusted_sample_size = int(
                            2 * n_patients_per_arm * interim_point
                        )
                        break
                    if interim_effect < futility_threshold:
                        # Stop for futility
                        adjusted_sample_size = int(
                            2 * n_patients_per_arm * interim_point
                        )
                        break

    return int(treatment_outcomes), int(control_outcomes), adjusted_sample_size


def _update_beliefs(
    n_samples: int,
    treatment_effect: np.ndarray,
    control_rate: np.ndarray,
    true_te: float,
    true_cr: float,
) -> tuple[np.ndarray, np.ndarray]:
    """Update beliefs based on simulated trial data."""
    updated_treatment_effect = np.zeros(n_samples)
    updated_control_rate = np.zeros(n_samples)

    # Data precision (simplified)
    data_precision = 100.0

    for i in range(n_samples):
        # Prior mean and variance for treatment effect
        prior_mean_te = treatment_effect[i]
        prior_var_te = 0.05**2  # Assumed prior variance
        prior_precision_te = 1.0 / prior_var_te

        # Posterior precision and mean
        posterior_precision_te = prior_precision_te + data_precision
        posterior_var_te = 1.0 / posterior_precision_te
        # Simulate a data-based estimate
        data_estimate_te = np.random.normal(
            true_te, 0.01
        )  # Small noise around true value
        posterior_mean_te = (
            prior_precision_te * prior_mean_te + data_precision * data_estimate_te
        ) / posterior_precision_te

        updated_treatment_effect[i] = np.random.normal(
            posterior_mean_te, np.sqrt(posterior_var_te)
        )

    for i in range(n_samples):
        # Prior mean and variance for control rate
        prior_mean_cr = control_rate[i]
        prior_var_cr = 0.05**2  # Assumed prior variance
        prior_precision_cr = 1.0 / prior_var_cr

        # Posterior precision and mean
        posterior_precision_cr = prior_precision_cr + data_precision
        posterior_var_cr = 1.0 / posterior_precision_cr
        # Simulate a data-based estimate
        data_estimate_cr = np.random.normal(
            true_cr, 0.01
        )  # Small noise around true value
        posterior_mean_cr = (
            prior_precision_cr * prior_mean_cr + data_precision * data_estimate_cr
        ) / posterior_precision_cr

        updated_control_rate[i] = np.random.normal(
            posterior_mean_cr, np.sqrt(posterior_var_cr)
        )

    return updated_treatment_effect, updated_control_rate


def _calculate_net_benefits(
    n_samples: int,
    updated_treatment_effect: np.ndarray,
    updated_control_rate: np.ndarray,
    cost_per_patient: np.ndarray,
    treatment_outcomes: int,
    control_outcomes: int,
    adjusted_sample_size: int,
) -> np.ndarray:
    """Calculate net benefits using updated beliefs."""
    n_strategies = 2
    net_benefits = np.zeros((n_samples, n_strategies))

    for i in range(n_samples):
        te = updated_treatment_effect[i]
        cr = updated_control_rate[i]
        cpp = cost_per_patient[i]

        # Ensure rates are between 0 and 1
        _ = np.clip(cr + te, 0, 1)
        cr = np.clip(cr, 0, 1)

        adjusted_cost = adjusted_sample_size * cpp

        control_benefit = control_outcomes * 1000
        net_benefits[i, 0] = control_benefit - adjusted_cost

        treatment_benefit = treatment_outcomes * 1000
        net_benefits[i, 1] = treatment_benefit - adjusted_cost

    net_benefits += np.random.normal(0, 500, net_benefits.shape)
    return net_benefits


def bayesian_adaptive_trial_simulator(
    psa_samples: PSASample,
    base_design: TrialDesign,
    adaptive_rules: dict[str, object],
    true_parameters: dict[str, float] | None = None,
) -> NetBenefitArray:
    """Simulate a Bayesian adaptive trial with belief updating.

    Parameters
    ----------
    psa_samples : ParameterSet
        PSA samples representing parameter uncertainty.
    base_design : TrialDesign
        Trial design before adaptive modifications.
    adaptive_rules : dict[str, object]
        Rules describing interim analyses and early stopping behavior.
    true_parameters : dict[str, float], optional
        Optional true parameter values used to generate the simulated trial.

    Returns
    -------
    ValueArray
        Net-benefit samples after Bayesian updating.

    Notes
    -----
    The implementation is a testing-oriented approximation of a Bayesian
    adaptive design rather than a fully general trial simulator.
    """
    n_samples = psa_samples.n_samples

    # If no true parameters provided, sample from the PSA samples
    if true_parameters is None:
        true_idx = np.random.randint(0, n_samples)
        true_parameters = {
            name: values[true_idx] for name, values in psa_samples.parameters.items()
        }

    # Extract relevant parameters
    treatment_effect = psa_samples.parameters.get(
        "treatment_effect", np.random.normal(0.1, 0.05, n_samples)
    )
    control_rate = psa_samples.parameters.get(
        "control_rate", np.random.normal(0.3, 0.05, n_samples)
    )
    cost_per_patient = psa_samples.parameters.get(
        "cost_per_patient", np.random.normal(5000, 500, n_samples)
    )

    # Get true values for simulation
    true_te = true_parameters.get("treatment_effect", 0.1)
    true_cr = true_parameters.get("control_rate", 0.3)
    _ = true_parameters.get("cost_per_patient", 5000)

    # Ensure rates are between 0 and 1
    true_treatment_rate = np.clip(true_cr + true_te, 0, 1)
    true_cr = np.clip(true_cr, 0, 1)

    n_patients_per_arm = 100  # Base sample size per arm
    treatment_outcomes, control_outcomes, adjusted_sample_size = (
        _simulate_trial_and_interims(
            true_treatment_rate, true_cr, n_patients_per_arm, adaptive_rules
        )
    )

    updated_treatment_effect, updated_control_rate = _update_beliefs(
        n_samples, treatment_effect, control_rate, true_te, true_cr
    )

    net_benefits = _calculate_net_benefits(
        n_samples,
        updated_treatment_effect,
        updated_control_rate,
        cost_per_patient,
        treatment_outcomes,
        control_outcomes,
        adjusted_sample_size,
    )
    import xarray as xr

    dataset = xr.Dataset(
        {"net_benefit": (("n_samples", "n_strategies"), net_benefits)},
        coords={
            "n_samples": np.arange(n_samples),
            "n_strategies": np.arange(2),
            "strategy": ("n_strategies", ["Control Only", "With Treatment"]),
        },
    )
    return NetBenefitArray(dataset=dataset)


def adaptive_evsi(
    adaptive_trial_simulator: AdaptiveTrialEconomicSim,
    psa_prior: PSASample,
    base_trial_design: TrialDesign,  # Initial design before adaptation
    adaptive_rules: dict[str, object],  # Specification of adaptation rules
    # wtp: float, # Often implicit
    population: float | None = None,
    discount_rate: float | None = None,
    time_horizon: float | None = None,
    n_outer_loops: int = 10,
    n_inner_loops: int = 50,
    # method_args for simulation, e.g., number of trial simulations
    **kwargs: object,
) -> float:
    """Calculate expected value of sample information for an adaptive trial.

    Parameters
    ----------
    adaptive_trial_simulator : callable
        Simulator that produces net-benefit samples for an adaptive design.
    psa_prior : ParameterSet
        Prior PSA sample representing current uncertainty.
    base_trial_design : TrialDesign
        Initial trial design before adaptation.
    adaptive_rules : dict[str, object]
        Adaptive rules such as interim timings and stopping criteria.
    population : float, optional
        Population size for population scaling.
    discount_rate : float, optional
        Annual discount rate used for population scaling.
    time_horizon : float, optional
        Time horizon in years for population scaling.
    n_outer_loops : int, default=10
        Number of outer Monte Carlo draws.
    n_inner_loops : int, default=50
        Number of inner Monte Carlo draws.
    **kwargs : object
        Additional simulator-specific arguments.

    Returns
    -------
    float
        Adaptive EVSI on a per-decision basis unless population scaling is
        requested.
    """
    # Validate inputs
    if not callable(adaptive_trial_simulator):
        raise_input_error("`adaptive_trial_simulator` must be a callable function.")
    if not isinstance(psa_prior, PSASample):
        raise_input_error("`psa_prior` must be a PSASample object.")
    if not isinstance(base_trial_design, TrialDesign):
        raise_input_error("`base_trial_design` must be a TrialDesign object.")
    if not isinstance(adaptive_rules, dict):
        raise_input_error("`adaptive_rules` must be a dictionary.")
    if n_outer_loops <= 0 or n_inner_loops <= 0:
        raise_input_error("n_outer_loops and n_inner_loops must be positive.")

    # 1. Calculate max_d E[NB(d) | Prior Info] using a standard (non-adaptive) economic model run.
    #    This is the baseline expected net benefit of the optimal decision with current info.
    nb_array_prior = adaptive_trial_simulator(
        psa_prior, base_trial_design, adaptive_rules
    )
    mean_nb_per_strategy_prior = np.mean(nb_array_prior.numpy_values, axis=0)
    max_expected_nb_current_info: float = np.max(mean_nb_per_strategy_prior)

    # 2. Outer loop (simulating different potential "realities" or "true parameter sets" theta_j):
    #    For j = 1 to N_outer_realities (drawn from psa_prior):
    #        Let theta_j be the "true" state of the world for this simulation.
    #        a. Inner loop (simulating multiple adaptive trial runs under reality theta_j):
    #           For k = 1 to N_inner_trial_sims:
    #               - Simulate one full adaptive trial path (data generation at interims,
    #                 application of adaptive rules, final data D_jk) assuming theta_j is true.
    #                 The path itself is stochastic due to data variability even if theta_j is fixed.
    #               - At the end of this simulated trial path (could be early stop or full completion),
    #                 we have a posterior P(theta | D_jk, theta_j_was_true_for_sim).
    #                 More simply, the simulator `adaptive_trial_simulator` might directly give
    #                 E_theta|D_jk [NB(d, theta|D_jk)] for each d.
    #               - Let V_jk = max_d E_theta|D_jk [NB(d, theta|D_jk)].
    #        b. Average V_jk over the N_inner_trial_sims to get E_D|theta_j [max_d E_theta|D [NB(d,theta|D)]].
    #           Let this be V_j_bar.

    max_nb_post_study = []
    for _ in range(n_outer_loops):
        # Sample a "true" parameter set from the prior
        true_params_idx = np.random.randint(0, psa_prior.n_samples)
        true_parameters = {
            name: values[true_params_idx]
            for name, values in psa_prior.parameters.items()
        }

        # Create a temporary simulator that uses these true parameters
        def simulator_with_true_params(
            psa_samples: PSASample,
            design: TrialDesign,
            rules: dict[str, object],
            true_params: dict[str, object] = true_parameters,
        ) -> NetBenefitArray:
            return bayesian_adaptive_trial_simulator(
                psa_samples, design, rules, true_params
            )

        try:
            # Simulate the adaptive trial with the true parameters
            nb_array_post = simulator_with_true_params(
                psa_prior, base_trial_design, adaptive_rules
            )
            mean_nb_per_strategy_post = np.mean(nb_array_post.numpy_values, axis=0)
            max_nb_post_study.append(np.max(mean_nb_per_strategy_post))
        except Exception:
            # If the simulator fails, use the prior value
            max_nb_post_study.append(max_expected_nb_current_info)

    # 3. Calculate E_theta [ E_D|theta [max_d E_theta|D [NB(d,theta|D)]] ] = mean(V_j_bar) over N_outer_realities.
    #    This is the overall expected value of making decisions after running the adaptive trial.
    expected_max_nb_post_study: float = np.mean(max_nb_post_study)

    # 4. Adaptive EVSI = E_theta [ E_D|theta [...] ] - max_d E[NB(d) | Prior Info]
    per_decision_adaptive_evsi = (
        expected_max_nb_post_study - max_expected_nb_current_info
    )
    per_decision_adaptive_evsi = max(0.0, per_decision_adaptive_evsi)

    # Population scaling
    if population is not None and time_horizon is not None:
        if population <= 0:
            raise_input_error("Population must be positive.")
        if time_horizon <= 0:
            raise_input_error("Time horizon must be positive.")

        dr = discount_rate if discount_rate is not None else 0.0
        if not (0 <= dr <= 1):
            raise_input_error("Discount rate must be between 0 and 1.")

        annuity = (
            (1 - (1 + dr) ** -time_horizon) / dr if dr > 0 else float(time_horizon)
        )
        return per_decision_adaptive_evsi * population * annuity

    return float(per_decision_adaptive_evsi)


if __name__ == "__main__":  # pragma: no cover
    print("--- Testing adaptive.py ---")

    # Add local imports for classes used in this test block
    import numpy as np  # np is used by NetBenefitArray call and PSASample

    from voiage.schema import (
        DecisionOption as TrialArm,
    )
    from voiage.schema import (
        ParameterSet as PSASample,
    )
    from voiage.schema import TrialDesign
    from voiage.schema import (
        ValueArray as NetBenefitArray,
    )

    # Simple adaptive trial simulator for testing
    def simple_adaptive_sim(
        psa: PSASample,
        design: TrialDesign,
        rules: dict[str, object],
    ) -> NetBenefitArray:
        """Run simple adaptive trial simulator for testing."""
        n_samples = psa.n_samples
        # Create net benefits for 2 strategies
        nb_values = np.random.rand(n_samples, 2) * 1000
        # Make strategy 1 slightly better on average
        nb_values[:, 1] += 100

        import xarray as xr

        dataset = xr.Dataset(
            {"net_benefit": (("n_samples", "n_strategies"), nb_values)},
            coords={
                "n_samples": np.arange(n_samples),
                "n_strategies": np.arange(2),
                "strategy": ("n_strategies", ["Standard Care", "New Treatment"]),
            },
        )
        return NetBenefitArray(dataset=dataset)

    # Create test parameter set
    dummy_psa = PSASample.from_numpy_or_dict({"p": np.random.rand(50)})

    # Create test trial design
    dummy_design = TrialDesign(
        arms=[
            TrialArm(name="Treatment A", sample_size=100),
            TrialArm(name="Treatment B", sample_size=100),
        ]
    )

    # Create test adaptive rules
    dummy_rules = {
        "interim_analysis_points": [0.5],
        "early_stopping_rules": {"efficacy": 0.95, "futility": 0.1},
    }

    # Test adaptive_evsi function
    print("Testing adaptive_evsi...")
    evsi_value = adaptive_evsi(
        adaptive_trial_simulator=simple_adaptive_sim,
        psa_prior=dummy_psa,
        base_trial_design=dummy_design,
        adaptive_rules=dummy_rules,
        n_outer_loops=3,
        n_inner_loops=5,
    )
    print(f"Adaptive EVSI: {evsi_value}")

    # Test with population scaling
    print("\nTesting adaptive_evsi with population scaling...")
    evsi_value_scaled = adaptive_evsi(
        adaptive_trial_simulator=simple_adaptive_sim,
        psa_prior=dummy_psa,
        base_trial_design=dummy_design,
        adaptive_rules=dummy_rules,
        population=100000,
        time_horizon=10,
        discount_rate=0.03,
        n_outer_loops=3,
        n_inner_loops=5,
    )
    print(f"Scaled Adaptive EVSI: {evsi_value_scaled}")

    # Test input validation
    print("\nTesting input validation...")
    try:
        # Test invalid adaptive_trial_simulator
        adaptive_evsi(
            adaptive_trial_simulator="not a function",  # type: ignore[arg-type]
            psa_prior=dummy_psa,
            base_trial_design=dummy_design,
            adaptive_rules=dummy_rules,
        )
    except InputError as e:
        print(f"Caught expected error for invalid simulator: {e}")

    try:
        # Test invalid psa_prior
        adaptive_evsi(
            adaptive_trial_simulator=simple_adaptive_sim,
            psa_prior="not a psa",  # type: ignore[arg-type]
            base_trial_design=dummy_design,
            adaptive_rules=dummy_rules,
        )
    except InputError as e:
        print(f"Caught expected error for invalid PSA: {e}")

    try:
        # Test invalid base_trial_design
        adaptive_evsi(
            adaptive_trial_simulator=simple_adaptive_sim,
            psa_prior=dummy_psa,
            base_trial_design="not a design",  # type: ignore[arg-type]
            adaptive_rules=dummy_rules,
        )
    except InputError as e:
        print(f"Caught expected error for invalid design: {e}")

    try:
        # Test invalid adaptive_rules
        adaptive_evsi(
            adaptive_trial_simulator=simple_adaptive_sim,
            psa_prior=dummy_psa,
            base_trial_design=dummy_design,
            adaptive_rules="not a dict",  # type: ignore[arg-type]
        )
    except InputError as e:
        print(f"Caught expected error for invalid rules: {e}")

    try:
        # Test invalid loop parameters
        adaptive_evsi(
            adaptive_trial_simulator=simple_adaptive_sim,
            psa_prior=dummy_psa,
            base_trial_design=dummy_design,
            adaptive_rules=dummy_rules,
            n_outer_loops=0,
        )
    except InputError as e:
        print(f"Caught expected error for invalid loop params: {e}")

    print("--- adaptive.py tests completed ---")
