# voiage/config.py

"""
Global configuration settings for the voiage library.

This module defines global settings that control the default behavior of
voiage functions. These settings include numerical precision, computation
backend, and default parameters for various analyses.

Users can import these settings directly or use the provided functions
(if implemented) to manage them.
"""

import numpy as np

# --- Numerical Precision ---
# Default data type for floating point calculations.
# Using float64 for higher precision, common in scientific computing.
DEFAULT_DTYPE = np.float64

# --- Backend Configuration ---
# Placeholder for backend selection (e.g., "numpy", "jax")
# This could be used by methods to switch their computation engine.
# Actual implementation of backend switching would be more involved.
DEFAULT_COMPUTATION_BACKEND = "numpy"  # Options: "numpy", "jax"

# --- Monte Carlo Sampling ---
# Default number of samples for Monte Carlo simulations if not specified by the user.
DEFAULT_MC_SAMPLES = 10000

# --- EVSI Specifics ---
# Default regression method for EVSI metamodeling if not specified.
# Options could include "gam", "gp", "bart", "rf" (Random Forest), etc.
DEFAULT_EVSI_REGRESSION_METHOD = "gam"

# --- Plotting ---
# Default settings for plots generated by pyvoi.plot (if any)
# For example, default figure size, DPI, or color palettes.


# --- Logging Configuration ---
# Basic logging setup can be initiated here if desired,
# though often done in __init__.py or by the application using the library.


# --- Other Global Settings ---
# Add any other library-wide settings here.
# For example, default Willingness-To-Pay (WTP) thresholds if applicable,
# though these are usually specific to an analysis.


# --- Functions to get/set configuration ---
# Optionally, provide functions to allow users to modify these settings at runtime.
# This needs careful consideration to avoid unexpected behavior if settings are changed mid-analysis.
