# pyvoi/config.py

"""Global configuration settings for the pyVOI library."""

import numpy as np

# --- Numerical Precision ---
# Default data type for floating point calculations.
# Using float64 for higher precision, common in scientific computing.
DEFAULT_DTYPE = np.float64

# --- Backend Configuration ---
# Placeholder for backend selection (e.g., "numpy", "jax")
# This could be used by methods to switch their computation engine.
# Actual implementation of backend switching would be more involved.
DEFAULT_COMPUTATION_BACKEND = "numpy"  # Options: "numpy", "jax"

# --- Monte Carlo Sampling ---
# Default number of samples for Monte Carlo simulations if not specified by the user.
DEFAULT_MC_SAMPLES = 10000

# --- EVSI Specifics ---
# Default regression method for EVSI metamodeling if not specified.
# Options could include "gam", "gp", "bart", "rf" (Random Forest), etc.
DEFAULT_EVSI_REGRESSION_METHOD = "gam"

# --- Plotting ---
# Default settings for plots generated by pyvoi.plot (if any)
# For example, default figure size, DPI, or color palettes.
# import matplotlib.pyplot as plt
# DEFAULT_FIGSIZE = (10, 6)
# DEFAULT_DPI = 100
# DEFAULT_COLOR_CYCLE = plt.rcParams['axes.prop_cycle'].by_key()['color']


# --- Logging Configuration ---
# Basic logging setup can be initiated here if desired,
# though often done in __init__.py or by the application using the library.
# import logging
# LOGGING_LEVEL = logging.INFO
# LOGGING_FORMAT = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'


# --- Other Global Settings ---
# Add any other library-wide settings here.
# For example, default Willingness-To-Pay (WTP) thresholds if applicable,
# though these are usually specific to an analysis.
# DEFAULT_WTP_THRESHOLD = 50000


# --- Functions to get/set configuration ---
# Optionally, provide functions to allow users to modify these settings at runtime.
# This needs careful consideration to avoid unexpected behavior if settings are changed mid-analysis.

# _config_store = {
#     "DEFAULT_DTYPE": DEFAULT_DTYPE,
#     "DEFAULT_COMPUTATION_BACKEND": DEFAULT_COMPUTATION_BACKEND,
#     "DEFAULT_MC_SAMPLES": DEFAULT_MC_SAMPLES,
# }

# def get_config(key):
#     return _config_store.get(key)

# def set_config(key, value):
#     if key in _config_store:
#         # Add validation if necessary
#         _config_store[key] = value
#     else:
#         raise KeyError(f"Invalid configuration key: {key}")

# Example:
# To use in other modules:
# from .config import DEFAULT_DTYPE
# array = np.array([1.0, 2.0], dtype=DEFAULT_DTYPE)

# from .config import get_config
# dtype = get_config("DEFAULT_DTYPE")

# print(f"pyVOI is configured to use dtype: {DEFAULT_DTYPE}")
# print(f"pyVOI default Monte Carlo samples: {DEFAULT_MC_SAMPLES}")
