name = "Voiage"
uuid = "8c7ad020-41fd-4d68-9c3f-5d4e11c48f1f"
authors = ["voiage Contributors <voiage@users.noreply.github.com>"]
version = "0.2.1"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
JSON = "0.21"
julia = "1.10"
