name = "Voiage"
uuid = "8c7ad020-41fd-4d68-9c3f-5d4e11c48f1f"
authors = ["Dylan Mordaunt <voiage@users.noreply.github.com>"]
version = "2.2.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JSON", "Test"]

[compat]
Aqua = "0.8"
JSON = "0.21"
Libdl = "1.10"
Test = "1.10"
julia = "1.10"
