{% set name = "voiage" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: placeholder_sha256_hash

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - voiage = voiage.cli:main

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=45
    - wheel
  run:
    - python >=3.8
    - numpy >=1.20.0
    - scipy >=1.7.0
    - pandas >=1.3.0
    - xarray >=0.18.0
    - matplotlib >=3.4.0
    - seaborn >=0.11.0
    - scikit-learn >=1.0.0
    - jax >=0.2.0
    - jaxlib >=0.1.65

test:
  imports:
    - voiage
    - voiage.analysis
    - voiage.schema
  commands:
    - pip check
    - voiage --help
  requires:
    - pip

about:
  home: https://github.com/doughnut/voiage
  summary: A Python library for Value of Information analysis
  description: |
    voiage is a Python library for Value of Information (VOI) analysis, 
    designed to provide a comprehensive, open-source toolkit for researchers 
    and decision-makers. It implements core VOI methods including EVPI, EVPPI, 
    and EVSI, as well as advanced methods for adaptive trial designs, network 
    meta-analyses, and structural uncertainty.
  dev_url: https://github.com/doughnut/voiage
  doc_url: https://voiage.readthedocs.io
  license: MIT
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - doughnut