#!/usr/bin/env python3
"""Generate the public VOI/VOP software feature matrix from registries."""

from __future__ import annotations

import argparse
from collections import Counter
import json
from pathlib import Path
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
LANDSCAPE = ROOT / "specs" / "software-landscape"
OUTPUT = (
    ROOT
    / "docs"
    / "astro-site"
    / "src"
    / "content"
    / "docs"
    / "software-feature-matrix.mdx"
)


def _load(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise TypeError(f"{path} must contain an object")
    return value


def _cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _render() -> str:
    registry = _load(LANDSCAPE / "registry.json")
    method_registry = _load(LANDSCAPE / "methods.json")
    evidence_registry = _load(LANDSCAPE / "method-evidence.json")
    gap_report = _load(LANDSCAPE / "gap-report.json")
    method_evidence = {
        item["method_id"]: item for item in evidence_registry["coverage"]
    }
    implementation_evidence = {
        item["method_id"]: item
        for item in _load(LANDSCAPE / "implementation-evidence.json")["records"]
    }
    tools = sorted(
        registry["tools"], key=lambda item: (item["ecosystem"], item["name"].lower())
    )
    methods = sorted(method_registry["methods"], key=lambda item: item["id"])
    states = Counter(
        feature["parity_state"] for tool in tools for feature in tool["features"]
    )
    ecosystems = Counter(tool["ecosystem"] for tool in tools)

    lines = [
        "---",
        "title: VOI and related software feature matrix",
        "description: Evidence-linked comparison generated from the VOIAGE software landscape registry",
        "---",
        "",
        "{/* Generated by scripts/generate_voi_feature_matrix.py; edit the registries, not this file. */}",
        "",
        f"Snapshot date: **{registry['searched_on']}**. Review due: **{registry['review_due']}**.",
        "",
        "This is a reproducible candidate census, not a claim that search engines expose every",
        "library. Direct decision-VOI software is separated from modeling systems, web or",
        "commercial tools, and information-theoretic acquisition libraries. `planned` means",
        "the capability is not yet evidenced as equivalent in VOIAGE.",
        "",
        "## Coverage summary",
        "",
        f"- {len(tools)} software or binding records across {len(ecosystems)} ecosystems.",
        f"- {len(methods)} canonical VOI, VOP, estimator, visualization, and related-method records.",
        "- Parity dispositions: "
        + ", ".join(f"`{key}` {states[key]}" for key in sorted(states))
        + ".",
        f"- {gap_report['summary']['open_feature_gaps']} external feature gaps and "
        f"{gap_report['summary']['open_method_or_assurance_gaps']} method or "
        "assurance gaps remain routed to Conductor tracks.",
        "",
        "## Software landscape",
        "",
        "| Tool | Ecosystem | Category | Maintenance | Version | Feature groups |",
        "| --- | --- | --- | --- | --- | ---: |",
    ]
    for tool in tools:
        sources = tool["authoritative_sources"]
        name = f"[{_cell(tool['name'])}]({_cell(sources[0])})"
        lines.append(
            "| "
            + " | ".join(
                [
                    name,
                    _cell(tool["ecosystem"]),
                    _cell(tool["tool_kind"]),
                    _cell(tool["maintenance"]),
                    _cell(tool["version"]),
                    str(len(tool["features"])),
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Observed features and VOIAGE disposition",
            "",
            "| Tool | Observed feature | Kind | Canonical methods | Disposition | VOIAGE evidence or gap |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    for tool in tools:
        for feature in sorted(tool["features"], key=lambda item: item["id"]):
            label = f"[{_cell(feature['label'])}]({_cell(feature['evidence'][0])})"
            lines.append(
                "| "
                + " | ".join(
                    [
                        _cell(tool["name"]),
                        label,
                        _cell(feature["kind"]),
                        ", ".join(f"`{item}`" for item in feature["method_ids"]),
                        f"`{_cell(feature['parity_state'])}`",
                        _cell(feature["voiage_evidence"]),
                    ]
                )
                + " |"
            )

    lines.extend(
        [
            "",
            "## Canonical method coverage",
            "",
            "| ID | Method or analysis | Class | MoSCoW | VOIAGE state | Maturity | Authority | Evidence state | Decision boundary | Promotion gate |",
            "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    lines.extend(
        (
            "| "
            + " | ".join(
                [
                    f"`{_cell(method['id'])}`",
                    _cell(method["label"]),
                    _cell(method["class"]),
                    _cell(method["moscow"]),
                    f"`{_cell(method['voiage_state'])}`",
                    f"`{_cell(method['maturity'])}`",
                    f"`{_cell(implementation_evidence.get(method['id'], {}).get('authority_state', 'not-implemented'))}`",
                    f"`{_cell(method_evidence[method['id']]['review_state'])}`",
                    f"`{_cell(method_evidence[method['id']]['decision_boundary'])}`",
                    f"`{_cell(method_evidence[method['id']]['promotion_gate'])}`",
                ]
            )
            + " |"
        )
        for method in methods
    )

    lines.extend(
        [
            "",
            "## Interpretation and exclusions",
            "",
            "- `native` and `equivalent` require VOIAGE-owned execution; no competing VOI",
            "  package may be required at runtime.",
            "- `adapter` is migration or interchange support, not delegated numerical authority.",
            "- `not-reproducible` is used for behavior that cannot currently be independently",
            "  observed or pinned, especially proprietary and inactive web tools.",
            "- General model construction, posterior inference, and generic acquisition",
            "  optimization remain delegated when they are not themselves VOI estimands.",
            "- EIG, BALD, entropy search, and similar scores are not called economic VOI unless",
            "  a downstream decision and utility or loss are explicit.",
            "- Positive external parity claims name competitor-free fixtures in",
            "  `specs/software-landscape/parity-fixtures.json`; all other gaps are routed",
            "  by `specs/software-landscape/gap-report.json`.",
            "",
            "The source registry, recorded searches, versions, licenses, and limitations are in",
            "[`specs/software-landscape/registry.json`](https://github.com/edithatogo/voiage/tree/main/specs/software-landscape).",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    """Write the generated matrix, or verify that it is current."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = _render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print(
                "software feature matrix is stale; run scripts/generate_voi_feature_matrix.py",
                file=sys.stderr,
            )
            return 1
        print("software feature matrix is current")
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
