#!/usr/bin/env bash
set -euo pipefail

repo_root=$(git rev-parse --show-toplevel)
mode=${1:---syntax}
case "$mode" in
  --syntax|--spec|--build) ;;
  *) echo 'usage: validate_hpc_recipes.sh [--syntax|--spec|--build]' >&2; exit 2 ;;
esac
python3 - "$repo_root" <<'PY'
import ast
from pathlib import Path
import sys
root = Path(sys.argv[1])
for path in [root / 'packaging/spack/package.py', *sorted((root / 'packaging/easybuild').glob('voiage-2.2.0-*.eb'))]:
    ast.parse(path.read_text(), filename=str(path))
    print(f'Syntax passed: {path.name}')
print('Syntax is not dependency concretization, installation, or module-load evidence.')
PY
[[ "$mode" == --syntax ]] && exit 0

if [[ -n "${HPC_VALIDATION_WORK_DIR:-}" ]]; then
  work_dir=$HPC_VALIDATION_WORK_DIR
  mkdir "$work_dir"  # Refuse to overwrite an earlier evidence directory.
else
  work_dir=$(mktemp -d)
  trap 'rm -rf "$work_dir"' EXIT
fi
spack_repo="$work_dir/spack-repo"
mkdir -p "$spack_repo/packages/py-voiage"
printf 'repo:\n  namespace: voiage_hpc\n' > "$spack_repo/repo.yaml"
cp "$repo_root/packaging/spack/package.py" "$spack_repo/packages/py-voiage/package.py"
export SPACK_USER_CONFIG_PATH="$work_dir/spack-config"
export SPACK_USER_CACHE_PATH="$work_dir/spack-cache"
spack repo add --scope user "$spack_repo"
if [[ -n "${HPC_SPACK_CATALOG_COMMIT:-}" ]]; then
  spack config --scope user add "repos:builtin:commit:$HPC_SPACK_CATALOG_COMMIT"
fi
spack python -c 'import spack.repo; print(spack.repo.PATH.get_repo("builtin").root)'
python3 - "$work_dir/spack-cache/package_repos" <<'PYTHON'
from pathlib import Path
import subprocess
import sys
for path in Path(sys.argv[1]).iterdir():
    result = subprocess.run(["git", "-C", str(path), "rev-parse", "HEAD"], text=True, capture_output=True, check=False)
    if result.returncode == 0:
        print(f"Spack catalogue: {path} revision={result.stdout.strip()}")
PYTHON
spack spec py-voiage@2.2.0
for toolchain in 2023a 2024a; do
  recipe="$repo_root/packaging/easybuild/voiage-2.2.0-foss-$toolchain.eb"
  eb --check-style "$recipe"
  eb --dry-run --robot "$recipe"
done
[[ "$mode" == --spec ]] && exit 0

# Explicit opt-in: source builds may download dependencies and take hours.
spack install --test=root py-voiage@2.2.0
spack load --sh py-voiage@2.2.0 > "$work_dir/spack-load.sh"
# This file is generated by the selected, locally installed Spack executable.
source "$work_dir/spack-load.sh"
voiage --help
python -c "import voiage._core as c; assert c.runtime_info()['engine'] == 'rust'"
for toolchain in 2023a 2024a; do
  eb --robot "$repo_root/packaging/easybuild/voiage-2.2.0-foss-$toolchain.eb"
done
